Repository raduchistest/acs-2020-2, pull requests merged in 2020-10, with the labels that each got.

#1 added Vlad Stanescu tasks
  vladstanescu-dir/helloworld.cpp
  vladstanescu-dir/vladstanescu.txt
Labels: good first issue

#2 Stefanprecup
  stefanprecup-dir/stefanprecup.txt
  stefanprecup.txt
Labels: bug, documentation, duplicate, enhancement, good first issue, help wanted, invalid, question, wontfix

#4 Mihailuca branch
  mihailuca-dir/hello-world.cpp
  mihailuca-dir/mihailuca.txt
Labels: bug, documentation, duplicate, enhancement, good first issue, help wanted, invalid, wontfix
